# Sample configuration file for Sidekiq.
# Options here can still be overridden by cmd line args.
# Place this file at config/sidekiq.yml and Sidekiq will
# pick it up automatically.
---
:verbose: false

# Sidekiq will run this file through ERB when reading it so you can
# even put in dynamic logic, like a host-specific queue.
# http://www.mikeperham.com/2013/11/13/advanced-sidekiq-host-specific-queues/
# -q "${COMPOSE_PROJECT_NAME:-notset}_default" -q "${COMPOSE_PROJECT_NAME:-notset}_mailers" 
:queues:
  - <%= "#{ENV['COMPOSE_PROJECT_NAME'] || 'notset'}_default" %>
  - <%= "#{ENV['COMPOSE_PROJECT_NAME'] || 'notset'}_mailers" %>
  - <%= "#{ENV['COMPOSE_PROJECT_NAME'] || 'notset'}_storage_analysis" %>
  - <%= "#{ENV['COMPOSE_PROJECT_NAME'] || 'notset'}_storage_purge" %>
  - <%= "#{ENV['COMPOSE_PROJECT_NAME'] || 'notset'}_mailbox_incinerate" %>
  - <%= "#{ENV['COMPOSE_PROJECT_NAME'] || 'notset'}_mailbox_routing" %>

# Scheduler

:scheduler:
  :dynamic: true
  :enabled: true
  